spring:
  profiles:
    include:
      - hook
slack:
  alarm:
    cron:
      monday-daily: 0 50 12 * * MON
      other-daily: 0 50 9 * * TUE-FRI
      monday-time-schedule: 0 0 13-17 * * MON
      other-time-schedule: 0 0 10-17 * * TUE-FRI
      off-work: 0 0 18 * * MON-FRI
    message:
      pretext:
        role: 죠-하! %s 역할 분담표 입니다! 데일리 담당자는 아래 링크를 통해 행아웃 만든 뒤, 링크 공유 부탁드려요!
        time-schedule: 정각 알림. %s입니다!
        off-work: 퇴근시간 알림! 고생많았습니다! 내일도 화이팅~ 죠-바~
      title:
        role: 데일리 행아웃 만들러 가기!
        time-schedule: Notion 타임 테이블에 다음 계획 등록하러 가기!
        off-work: 다음날 Notion 타임 테이블 추가하러 가기!
      title-link:
        role: https://hangouts.google.com/?hl=ko
        time-schedule: https://www.notion.so/30-7cc88d38f374414cab274099659aaa44
      text:
        role: 데일리 담당자는 위 링크로 가서 행아웃을 만들어주세요!
        time-schedule: 모든 근무 인원 타임 테이블에 다음 1시간 일정 추가해주세요! 일정 추가 후, 가벼운 스트레칭과 휴식을 통해 몸의 피로를 풀어주세요 😀
        off-work: 타임 테이블 관리자는 다음날 Notion 타임 테이블을 새로 추가해주세요!
